name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build and test
      run: xcodebuild clean build test -project TriangleApp.xcodeproj -scheme TriangleApp -destination 'platform=iOS Simulator,name=iPhone 11,OS=14.4' build test
